import Spritesmith from 'spritesmith';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Define paths
const sourceDirectory = path.resolve(__dirname, '..', 'Art/Pops/Icons');
const outputImage = path.resolve(__dirname, '..', 'Public/Icons/Pops.png');
const outputCss = path.resolve(__dirname, '..', 'Stylesheets/generated/_sprite.scss');

// 2. Get all icon files
const icons = fs.readdirSync(sourceDirectory).map(file => path.join(sourceDirectory, file));

// 3. Run Spritesmith
Spritesmith.run({ src: icons, padding: 5 }, (err, result) => {
    if (err) {
        throw err;
    }

    // 4. Write the output files
    fs.ensureDirSync(path.dirname(outputImage));
    fs.writeFileSync(outputImage, result.image); // Write the sprite image

    // 5. Generate the SCSS content
    let scssContent = '// This file is automatically generated. Do not edit.\n\n';
    scssContent += '$sprites: (\n';

    Object.entries(result.coordinates).forEach(([filepath, coords]) => {
        const name = path.basename(filepath, '.png');
        scssContent += `    ${name}: (\n`;
        scssContent += `        x: -${coords.x}px,\n`;
        scssContent += `        y: -${coords.y}px,\n`;
        scssContent += `        width: ${coords.width}px,\n`;
        scssContent += `        height: ${coords.height}px\n`;
        scssContent += `    ),\n`;
    });

    scssContent += ');\n';

    fs.writeFileSync(outputCss, scssContent); // Write the SCSS file

    console.log('✅ Spritesheet and SCSS generated successfully!');
});
