export enum TooltipType {
    PlanetCell = 'PlanetCell',

    // Pop Tooltips
    PopAccount = 'PopAccount',
    PopJobHelp = 'PopJobHelp',
    PopJobList = 'PopJobList',
    PopJobs = 'PopJobs',
    PopResourceIO = 'PopResourceIO',
    PopResourceOrigin = 'PopResourceOrigin',
    PopStockpile = 'PopStockpile',
    PopExplainPrice = 'PopExplainPrice',
    PopNeeds = 'PopNeeds',
    PopType = 'PopType',
    PopCashFlowItem = 'PopCashFlowItem',
    PopBudgetItem = 'PopBudgetItem',
    PopOwnershipCountry = 'PopOwnershipCountry',
    PopOwnershipCulture = 'PopOwnershipCulture',
    PopOwnershipGender = 'PopOwnershipGender',
    PopOwnershipSecurities = 'PopOwnershipSecurities',

    // Factory Tooltips
    FactoryAccount = 'FactoryAccount',
    FactorySize = 'FactorySize',
    FactoryResourceIO = 'FactoryResourceIO',
    FactoryStockpile = 'FactoryStockpile',
    FactoryExplainPrice = 'FactoryExplainPrice',
    FactorySummarizeEmployees = 'FactorySummarizeEmployees',
    FactoryNeeds = 'FactoryNeeds',
    FactoryOwnershipCountry = 'FactoryOwnershipCountry',
    FactoryOwnershipCulture = 'FactoryOwnershipCulture',
    FactoryOwnershipGender = 'FactoryOwnershipGender',
    FactoryOwnershipSecurities = 'FactoryOwnershipSecurities',
    FactoryCashFlowItem = 'FactoryCashFlowItem',
    FactoryBudgetItem = 'FactoryBudgetItem',

    // Building Tooltips
    BuildingAccount = 'BuildingAccount',
    BuildingActive = 'BuildingActive',
    BuildingVacant = 'BuildingVacant',
    BuildingResourceIO = 'BuildingResourceIO',
    BuildingStockpile = 'BuildingStockpile',
    BuildingExplainPrice = 'BuildingExplainPrice',
    BuildingNeeds = 'BuildingNeeds',
    BuildingOwnershipCountry = 'BuildingOwnershipCountry',
    BuildingOwnershipCulture = 'BuildingOwnershipCulture',
    BuildingOwnershipGender = 'BuildingOwnershipGender',
    BuildingOwnershipSecurities = 'BuildingOwnershipSecurities',
    BuildingCashFlowItem = 'BuildingCashFlowItem',
    BuildingBudgetItem = 'BuildingBudgetItem',

    MarketLiquidity = 'MarketLiquidity',
    MarketHistory = 'MarketHistory',

    TilePopRace = 'TilePopRace',
    TilePopOccupation = 'TilePopOccupation',
    TileIndustry = 'TileIndustry',
    TileResourceProduced = 'TileResourceProduced',
    TileResourceConsumed = 'TileResourceConsumed',
}
