#!/bin/bash

cd "$(dirname "$0")/.."

set -e

echo '🝮 Running unit tests 🝮'

swift test

Scripts/Build -s
Scripts/Build -j

Scripts/Build -x

echo '🝮 Running engine tests 🝮'

Scripts/Build -l -c release
# next step: compare outputs
Scripts/.build/release/engine-tests
Scripts/.build/release/engine-tests

echo '🝮 Running integration tests 🝮'

Scripts/Build -i -c release

cd Tests
npx tsc
npm test
