import GameEngine
import JavaScriptKit
import JavaScriptInterop

/// Represents a single instruction for the TypeScript renderer to build a piece of a tooltip.
/// This enum is the core of the type-safe blueprint generated by Swift.
@frozen public enum TooltipInstruction {
    /// A simple, non-indented heading.
    case header(UInt, ColorText)

    /// For displaying a single, standalone value, often with a sign.
    case factor(Label, Factor)
    /// For values that change over time, showing the current value and a delta.
    case ticker(Label, Ticker)
    /// For progress-like values, showing a value out of a total limit.
    case count(Label, Count)
}

extension TooltipInstruction: JavaScriptEncodable, ConvertibleToJSValue {
    /// A unified set of keys for all possible properties of a render instruction.
    /// This allows TypeScript to model the instruction as a tagged union.
    @frozen public enum ObjectKey: JSString {
        // Discriminating key
        case type

        case html

        case fortune
        case indent
        case label

        case value
        case delta
        case limit
        case sign
    }

    public func encode(to js: inout JavaScriptEncoder<ObjectKey>) {
        switch self {
        case .header(let indent, let html):
            js[.type] = "Header"
            js[.indent] = indent == 0 ? nil : indent
            js[.html] = html

        case .factor(let label, let factor):
            js[.type] = "Factor"
            js[.fortune] = label.fortune
            js[.indent] = label.indent == 0 ? nil : label.indent
            js[.label] = label.text

            js[.value] = factor.value
            js[.sign] = factor.sign

        case .ticker(let label, let ticker):
            js[.type] = "Ticker"
            js[.fortune] = label.fortune
            js[.indent] = label.indent == 0 ? nil : label.indent
            js[.label] = label.text

            js[.value] = ticker.value
            js[.delta] = ticker.delta
            js[.sign] = ticker.sign

        case .count(let label, let count):
            js[.type] = "Count"
            js[.fortune] = label.fortune
            js[.indent] = label.indent == 0 ? nil : label.indent
            js[.label] = label.text

            js[.value] = count.value
            js[.limit] = count.limit
            js[.sign] = count.sign
        }
    }
}
